# docker-compose.yml - Optional: For local development with Supabase
# Note: This uses Supabase cloud by default. For local Supabase, uncomment the services below.

version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DIRECT_URL=${DIRECT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped

  # Optional: Local Supabase (uncomment to use local Supabase instead of cloud)
  # supabase:
  #   image: supabase/postgres:15.1.0.147
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-password}
  #   volumes:
  #     - supabase-db:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   supabase-db:

